//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENH()
        {
            this.SO_THEO_DOI_SUC_KHOE = new HashSet<SO_THEO_DOI_SUC_KHOE>();
        }
    
        public int Ma_Benh { get; set; }
        public string Ten_Benh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_THEO_DOI_SUC_KHOE> SO_THEO_DOI_SUC_KHOE { get; set; }
    }
}
