//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BENH_NHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENH_NHAN()
        {
            this.LICH_CHAM_SOC = new HashSet<LICH_CHAM_SOC>();
            this.SO_THEO_DOI_SUC_KHOE = new HashSet<SO_THEO_DOI_SUC_KHOE>();
        }


        [Required(ErrorMessage = "Mã tài khoản không được để trống")]
        public int Ma_TK { get; set; }
        public int Ma_HGD { get; set; }
        public int Ma_Quyen { get; set; }

        [Required(ErrorMessage = "Họ tên không được để trống")]
        public string Ho_Ten { get; set; }

        [Required(ErrorMessage = "Ngày sinh không được để trống")]
        public System.DateTime Ngay_Sinh { get; set; }

        [Required(ErrorMessage = "Số CCCD không được để trống")]
        [RegularExpression(@"^\d{12}$", ErrorMessage = "Số CCCD phải đúng định dạng (12 chữ số)")]
        public string So_CCCD { get; set; }

        [Required(ErrorMessage = "Giới tính không được để trống")]
        public bool Gioi_Tinh { get; set; }

        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string Dia_Chi { get; set; }

        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        [RegularExpression(@"^\d{10,11}$", ErrorMessage = "Số điện thoại phải chứa từ 10 đến 11 chữ số")]
        public string So_Dien_Thoai { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8}$",
    ErrorMessage = "Mật khẩu phải chứa ít nhất 1 chữ số, 1 chữ cái, 1 ký tự đặc biệt và có độ dài 8 ký tự")]
        public string Mat_Khau { get; set; }
        public string So_BHYT { get; set; }
    
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
        public virtual HO_GIA_DINH HO_GIA_DINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_CHAM_SOC> LICH_CHAM_SOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_THEO_DOI_SUC_KHOE> SO_THEO_DOI_SUC_KHOE { get; set; }
    }
}
