//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DON_GIA_DICH_VU
    {
        public int Ma_Dich_Vu { get; set; }
        public System.DateTime Ngay_Gio { get; set; }
        [Required(ErrorMessage = "Đơn giá không được để trống")]
        public long Don_Gia { get; set; }
    
        public virtual DICH_VU_CHAM_SOC_NGUOI_BENH DICH_VU_CHAM_SOC_NGUOI_BENH { get; set; }
        public virtual THOI_DIEM THOI_DIEM { get; set; }
    }
}
