//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.LICH_CHAM_SOC1 = new HashSet<LICH_CHAM_SOC>();
        }
    
        public int So_Hoa_Don { get; set; }
        public System.DateTime Ngay_Gio { get; set; }
        public int Ma_Lich { get; set; }
        public int Ma_TK { get; set; }
        public long Tong_Tien { get; set; }
    
        public virtual LICH_CHAM_SOC LICH_CHAM_SOC { get; set; }
        public virtual THOI_DIEM THOI_DIEM { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn nhân viên")]
        public virtual NHAN_VIEN_CHAM_SOC NHAN_VIEN_CHAM_SOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_CHAM_SOC> LICH_CHAM_SOC1 { get; set; }
    }
}
