//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LICH_CHAM_SOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICH_CHAM_SOC()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int Ma_Lich { get; set; }
        public Nullable<int> So_Hoa_Don { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn dịch vụ")]
        public int Ma_Dich_Vu { get; set; }
        public Nullable<int> Ma_TK { get; set; }
        [Required(ErrorMessage = "Ngày bắt đầu không được để trống")]
        public System.DateTime Ngay_Bat_Dau { get; set; }
        [Required(ErrorMessage = "Số ngày thuê không được để trống")]
        [Range(1, int.MaxValue, ErrorMessage = "Số ngày thuê phải lớn hơn 0")]
        public int So_Ngay_Thue { get; set; }
        [Required]
        public bool Yeu_Cau_Chi_Dinh_NVCS { get; set; }
        public string Ten_NVCS_Muon_Chon { get; set; }
        [Required]
        public string Mo_Ta_Benh_Ly { get; set; }
        [Required]
        public string Ho_Ten_Benh_Nhan { get; set; }
        [Required]
        public string Dia_Chi_Noi_Cham_Soc { get; set; }
        [Required]
        public string So_Dien_Thoai_Nguoi_Thue { get; set; }
        public bool Trang_Thai { get; set; }
    
        public virtual BENH_NHAN BENH_NHAN { get; set; }
        public virtual DICH_VU_CHAM_SOC_NGUOI_BENH DICH_VU_CHAM_SOC_NGUOI_BENH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual HOA_DON HOA_DON1 { get; set; }
    }
}
