//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csdl_HTQLEntities : DbContext
    {
        public csdl_HTQLEntities()
            : base("name=csdl_HTQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAC_SI_GIA_DINH> BAC_SI_GIA_DINH { get; set; }
        public virtual DbSet<BENH> BENH { get; set; }
        public virtual DbSet<BENH_NHAN> BENH_NHAN { get; set; }
        public virtual DbSet<DICH_VU_CHAM_SOC_NGUOI_BENH> DICH_VU_CHAM_SOC_NGUOI_BENH { get; set; }
        public virtual DbSet<DON_GIA_DICH_VU> DON_GIA_DICH_VU { get; set; }
        public virtual DbSet<HO_GIA_DINH> HO_GIA_DINH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<LICH_CHAM_SOC> LICH_CHAM_SOC { get; set; }
        public virtual DbSet<NHAN_VIEN_CHAM_SOC> NHAN_VIEN_CHAM_SOC { get; set; }
        public virtual DbSet<PHAN_CONG_CHAM_SOC> PHAN_CONG_CHAM_SOC { get; set; }
        public virtual DbSet<QUAN_TRI_VIEN> QUAN_TRI_VIEN { get; set; }
        public virtual DbSet<QUYEN_TRUY_CAP> QUYEN_TRUY_CAP { get; set; }
        public virtual DbSet<SO_THEO_DOI_SUC_KHOE> SO_THEO_DOI_SUC_KHOE { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<THOI_DIEM> THOI_DIEM { get; set; }
    }
}
