//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHAN_CONG_CHAM_SOC
    {
        [Required(ErrorMessage = "Vui lòng chọn hộ gia đình")]
        public int? Ma_HGD { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn bác sĩ")]
        public int? Ma_TK { get; set; }
        [Required(ErrorMessage = "Thời gian bắt đầu không được để trống")]
        public System.DateTime Thoi_Gian_Bat_Dau { get; set; }
        [Required(ErrorMessage = "Thời gian kết thúc không được để trống")]
        public System.DateTime Thoi_Gian_Ket_Thuc { get; set; }
    
        public virtual BAC_SI_GIA_DINH BAC_SI_GIA_DINH { get; set; }
        public virtual HO_GIA_DINH HO_GIA_DINH { get; set; }
    }
}
