//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QUAN_TRI_VIEN
    {
        [Required(ErrorMessage = "Mã tài khoản không được để trống")]
        public int Ma_TK { get; set; }

        [Required(ErrorMessage = "Mã quyền không được để trống")]
        public int Ma_Quyen { get; set; }

        [Required(ErrorMessage = "Họ tên không được để trống")]
        public string Ho_Ten { get; set; }

        [Required(ErrorMessage = "Ngày sinh không được để trống")]
        public System.DateTime Ngay_Sinh { get; set; }

        [Required(ErrorMessage = "Số CCCD không được để trống")]
        [RegularExpression(@"^\d{12}$", ErrorMessage = "Số CCCD phải đúng định dạng (12 chữ số)")]
        public string So_CCCD { get; set; }

        [Required(ErrorMessage = "Giới tính không được để trống")]
        public bool Gioi_Tinh { get; set; }

        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string Dia_Chi { get; set; }

        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        [RegularExpression(@"^\d{10,11}$", ErrorMessage = "Số điện thoại phải chứa từ 10 đến 11 chữ số")]
        public string So_Dien_Thoai { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8}$",
    ErrorMessage = "Mật khẩu phải chứa ít nhất 1 chữ số, 1 chữ cái, 1 ký tự đặc biệt và có độ dài 8 ký tự")]
        public string Mat_Khau { get; set; }

        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
