//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SO_THEO_DOI_SUC_KHOE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SO_THEO_DOI_SUC_KHOE()
        {
            this.BENH = new HashSet<BENH>();
        }
    
        
        public int Ma_TK { get; set; }
        public int BAC_Ma_TK { get; set; }
        public System.DateTime Ngay_Gio { get; set; }
        public int So_Thu_Tu { get; set; }
        [Required(ErrorMessage = "Các thông số sức khỏe không được để trống")]
        public string Cac_Thong_So_Suc_Khoe { get; set; }
        [Required(ErrorMessage = "ĐƠn thuốc không được để trống")]
        public string Don_Thuoc { get; set; }
        [Required(ErrorMessage = "Chỉ định dinh dưỡng không được để trống")]
        public string Chi_Dinh_Dinh_Duong { get; set; }
        [Required(ErrorMessage = "Ghi chú thuê không được để trống")]
        public string Ghi_Chu { get; set; }
    
        public virtual BAC_SI_GIA_DINH BAC_SI_GIA_DINH { get; set; }
        public virtual BENH_NHAN BENH_NHAN { get; set; }
        public virtual THOI_DIEM THOI_DIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENH> BENH { get; set; }
    }
}
