//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DV_Y_TE_GIA_DINH
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOI_DIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THOI_DIEM()
        {
            this.DON_GIA_DICH_VU = new HashSet<DON_GIA_DICH_VU>();
            this.HOA_DON = new HashSet<HOA_DON>();
            this.SO_THEO_DOI_SUC_KHOE = new HashSet<SO_THEO_DOI_SUC_KHOE>();
        }

        public int Ma_TD { get; set; }

        public System.DateTime Ngay_Gio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_GIA_DICH_VU> DON_GIA_DICH_VU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_THEO_DOI_SUC_KHOE> SO_THEO_DOI_SUC_KHOE { get; set; }
    }
}
